name: passwd
description: A library for generating strong passwords.
version: 1.0.0
homepage: https://github.com/shervin-h/passwd
repository: https://github.com/shervin-h/passwd
issue_tracker: https://github.com/shervin-h/passwd/issues

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
